version: '3'
services:
  db:
    image: postgres:14-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=odys
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    restart: always

volumes:
  postgres_data:
